default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46193_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_46193_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>


#default: &default
#  adapter: mysql2
#  encoding: utf8mb4
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: root
#  password:
#  socket: /tmp/mysql.sock

#development:
#  <<: *default
#  database: furima_46193_development

#test:
#  <<: *default
#  database: furima_46193_test

#production:
#  <<: *default
#  database: furima_46193_production
#  username: furima_46193
#  password: <%= ENV["FURIMA_46193_DATABASE_PASSWORD"] %>
